name: Build and Deploy to McGill via FTP

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout latest code in master
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install Gridsome CLI
        run: npm install --global @gridsome/cli

      - name: Install dependencies
        run: npm install

      - name: Build dist files
        run: gridsome build

      - name: FTP Deploy
        uses: kevinpainchaud/simple-ftp-deploy-action@v1.0.1
        with:
          ftp_host: ${{ secrets.FTP_HOST }}
          ftp_username: ${{ secrets.FTP_USERNAME }}
          ftp_password: ${{ secrets.FTP_PASSWORD }}
          local_source_dir: dist
          dist_target_dir: "public_html"
          delete: "true"
          disable_ssl_certificate_verification: true
